export default {
  GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
};
